swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /api/v1
paths:
  /ecology/add_account:
    get:
      tags:
      - ecology
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: ""
  /ecology/add_formula:
    get:
      tags:
      - ecology
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: ""
  /ecology/add_user:
    get:
      tags:
      - ecology
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: ""
  /ecology/check:
    get:
      tags:
      - ecology
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: ""
  /ecology/create_new_warehouse:
    post:
      tags:
      - ecology
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: query
        name: user_id
        description: 当前用户的id   ---- 放在 header
        required: true
        type: string
      - in: query
        name: coin_number
        description: 铸(发)币的数量
        required: true
        type: string
      - in: query
        name: levelstr
        description: 等级数据
        required: true
        type: string
      responses:
        200____新增生态仓库:
          description: ""
  /ecology/create_user:
    post:
      tags:
      - ecology
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        200___测试:
          description: ""
  /ecology/operation_formula_list:
    post:
      tags:
      - ecology
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: query
        name: force_id
        description: 算力信息的id  如果是删除多条，　用　, 逗号隔开
        required: true
        type: string
      - in: query
        name: action
        description: 具体的操作　　delete=删除　update=更新　insert=新增    更新必须传这条数据的全部数据回来，id 除外，和新增一样，删除只要ｉｄ就够
        required: true
        type: string
      - in: query
        name: levelstr
        description: 等级名字
        required: true
        type: string
      - in: query
        name: low_hold
        description: 低位
        required: true
        type: string
      - in: query
        name: high_hold
        description: 高位
        required: true
        type: string
      - in: query
        name: return_multiple
        description: 杠杆
        required: true
        type: string
      - in: query
        name: hold_return_rate
        description: 本金自由算力
        required: true
        type: string
      - in: query
        name: recommend_return_rate
        description: 直推算力
        required: true
        type: string
      - in: query
        name: team_return_rate
        description: 动态算力
        required: true
        type: string
      responses:
        200___算力表信息修改:
          description: ""
  /ecology/operation_super_formula_list:
    post:
      tags:
      - ecology
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: query
        name: super_force_id
        description: 超级节点的算力信息的id  如果是删除多条，　用　, 逗号隔开
        required: true
        type: string
      - in: query
        name: action
        description: 具体的操作　　delete=删除　update=更新　insert=新增    更新必须传这条数据的全部数据回来，id 除外，和新增一样，删除只要id就够
        required: true
        type: string
      - in: query
        name: levelstr
        description: 等级名字
        required: true
        type: string
      - in: query
        name: coin_number
        description: 要求的持币数量
        required: true
        type: string
      - in: query
        name: force
        description: '算力　　要以小数的格式返回　　如 : 15% = 0.15'
        required: true
        type: string
      responses:
        200___超级节点算力表信息修改:
          description: ""
  /ecology/return_page_list_hostry:
    get:
      tags:
      - ecology
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: query
        name: ecology_id
        description: 生态仓库id的id
        type: string
      - in: query
        name: page
        description: 分页信息　－　当前页数
        required: true
        type: string
      - in: query
        name: pageSize
        description: 分页信息　－　每页数据量
        required: true
        type: string
      responses:
        200____交易的历史记录:
          description: ""
          schema:
            $ref: '#/definitions/models.HostryPageInfo_test'
  /ecology/show_ecology_index:
    get:
      tags:
      - ecology
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        200___生态首页展示:
          description: ""
          schema:
            $ref: '#/definitions/models.Ecology_index_ob_test'
  /ecology/show_formula_list:
    get:
      tags:
      - ecology
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        200__算力表显示后台操or用户查_都可:
          description: ""
          schema:
            $ref: '#/definitions/models.ForceTable_test'
  /ecology/show_super_formula_list:
    get:
      tags:
      - ecology
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        200__超级节点算力表显示后台操作or用户查看都可以:
          description: ""
          schema:
            $ref: '#/definitions/models.SuperForceTable_test'
  /ecology/to_change_into_USDD:
    post:
      tags:
      - ecology
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: query
        name: user_id
        description: 用户id   ---- 放在 header
        required: true
        type: string
      - in: query
        name: ecology_id
        description: 生态仓库id的id
        type: string
      - in: query
        name: coin_number
        description: 铸(发)币的数量
        required: true
        type: string
      responses:
        200___转USDD到生态仓库:
          description: ""
  /ecology/upgrade_warehouse:
    post:
      tags:
      - ecology
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: query
        name: user_id
        description: 用户id   ---- 放在 header
        required: true
        type: string
      - in: query
        name: ecology_id
        description: 生态仓库id的id
        type: string
      - in: query
        name: cion_number
        description: 铸(发)币的数量
        required: true
        type: string
      - in: query
        name: levelstr
        description: 升级后的等级
        required: true
        type: string
      responses:
        200____升级生态仓库:
          description: ""
  /ecology/yanshi:
    get:
      tags:
      - ecology
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: ""
definitions:
  models.Ecology_index_ob_test:
    title: Ecology_index_ob_test
    type: object
    properties:
      ecological_poject___生态项目:
        type: array
        items:
          $ref: '#/definitions/models.Formulaindex_test'
      ecological_poject_bool___是否有生态仓库没有就是false:
        type: boolean
      super_peer___超级节点信息:
        $ref: '#/definitions/models.SuperPeer_test'
      super_peer_bool__是否显示超级节点:
        type: boolean
      usdd___usdd数量:
        type: number
        format: double
  models.ForceTable_test:
    title: ForceTable_test
    type: object
    properties:
      high_hold___高位:
        type: integer
        format: int64
      hold_return_rate____自由算力:
        type: number
        format: double
      id__id:
        type: integer
        format: int64
      level___等级:
        type: string
      low_hold___充值或者升级的低位:
        type: integer
        format: int64
      recommend_return_rate____直推算力:
        type: number
        format: double
      return_multiple___杠杆:
        type: number
        format: double
      team_return_rate____动态算力__团队算力:
        type: number
        format: double
  models.Formulaindex_test:
    title: Formulaindex_test
    type: object
    properties:
      balance___投资总额:
        type: number
        format: double
      bocked_balance___持币数量:
        type: number
        format: double
      high_hold___高位:
        type: integer
        format: int64
      hold_return_rate___自由算力:
        type: number
        format: double
      id__生态仓库id:
        type: integer
        format: int64
      level___等级:
        type: string
      low_hold___低位:
        type: integer
        format: int64
      recommend_return_rate___直推算力:
        type: number
        format: double
      return_multiple___杠杆:
        type: number
        format: double
      team_return_rate____动态算力:
        type: number
        format: double
      to_day_rate___今日算力:
        type: number
        format: double
  models.HostryPageInfo_test:
    title: HostryPageInfo_test
    type: object
    properties:
      items___数据列表:
        type: array
        items:
          $ref: '#/definitions/models.HostryValues_test'
      page___分页信息:
        $ref: '#/definitions/models.Page_test'
  models.HostryValues_test:
    title: HostryValues_test
    type: object
    properties:
      account____生态仓库id:
        type: integer
        format: int64
      comment___评论_:
        type: string
      create_date___创建时间:
        type: string
      current_balance___本期余额:
        type: number
        format: double
      current_outlay____本期支出:
        type: number
        format: double
      current_revenue___上期支出:
        type: number
        format: double
      id:
        type: integer
        format: int64
      opening_balance___上期c余额:
        type: number
        format: double
      tx_id__任务id_:
        type: string
      user_id___:
        type: string
  models.Page_test:
    title: Page_test
    type: object
    properties:
      count___总数据量:
        type: integer
        format: int64
      current_page___当前页数:
        type: integer
        format: int64
      page_size___每页数据条数:
        type: integer
        format: int64
      total_page__总页数:
        type: integer
        format: int64
  models.SuperForceTable_test:
    title: SuperForceTable_test
    type: object
    properties:
      bonus_calculation____分红比例:
        type: number
        format: double
      coin_number_rule___币数:
        type: integer
        format: int64
      id__id:
        type: integer
        format: int64
      level___等级:
        type: string
  models.SuperPeer_test:
    title: SuperPeer_test
    type: object
    properties:
      level___超级节点的独立属性:
        type: string
      today_a_bouns___今日分红:
        type: number
        format: double
      usdd___总币数ForceTable_test:
        type: number
        format: double
